import { createI18n } from 'vue-i18n';

const messages = {
  en: {
    app: { title: "Sales Command Center" },
    nav: { home: "Home", dashboard: "Dashboard", pipeline: "Pipeline", team: "Team", coi: "COI", blog: "Blog", lists: "Lists" },
    auth: { signIn: "Sign In", signOut: "Sign Out", signingIn: "Signing in...", email: "Email", password: "Password" },
    common: { save: "Save", cancel: "Cancel", delete: "Delete", edit: "Edit", add: "Add", search: "Search", loading: "Loading...", loadingDashboard: "Loading dashboard...", noData: "No data available", confirm: "Confirm", yes: "Yes", no: "No", refresh: "Refresh", active: "active", days: "days", unassigned: "Unassigned", na: "N/A" },
    language: { select: "Language", en: "English", es: "Spanish", fr: "French" },
    login: { title: "Sign In", subtitle: "Use your account to access your tenant data.", emailPlaceholder: "you{'@'}example.com", passwordPlaceholder: "********", hint: "First-time bootstrap: set ADMIN_EMAIL and ADMIN_PASSWORD in .env and sign in with those values." },
    home: { badge: "Home", title: "Sales Command Center", subtitle: "Navigate between dashboard, pipeline, team, COI, and blog views", filteredProspects: "Filtered Prospects", activeStaff: "Active Staff Entries", securedValue: "Secured Value", coiRecords: "COI Records", dashboard: "Dashboard", dashboardDesc: "Top-line KPIs for approaches, meetings, proposals, and secured work.", dashboardCharts: "Dashboard Charts", dashboardChartsDesc: "See the KPI summary and visual trends together in one place.", pipeline: "Pipeline", pipelineDesc: "Detailed pipeline table with the working prospect view.", team: "Team", teamDesc: "Open the team report without digging through tabs.", coi: "COI", coiDesc: "Jump straight to referral development activity and records.", blog: "Blog", blogDesc: "Open the content workflow, saved inputs, drafts, and final posts.", todayGlance: "Today at a Glance", prospectName: "Prospect Name", businessName: "Business Name", teamMember: "Team Member", status: "Status", securedValueCol: "Secured Value", whatEachSection: "What Each Section Gives You", infoDashboard: "Dashboard now includes both headline numbers and charts.", infoTrends: "Visual trends sit directly under the KPI summary.", infoPipeline: "Pipeline is the working view for exporting and follow-up.", rowsLoaded: "Team rows loaded: {team} | COI rows loaded: {coi}" },
    dashboard: { badge: "Analytics", title: "Sales Dashboard", subtitle: "Real-time insights into your sales pipeline and team performance", totalProspects: "Total Pipeline Prospects", approachMeeting: "Approach → Meeting", meetingProposal: "Meeting → Proposal", proposalSecured: "Proposal → Secured", overallWinRate: "Overall Win Rate", pipelineValue: "Pipeline Value", workSecured: "Work Secured", outstandingProposals: "Outstanding proposals", totalClosedValue: "Total closed value", combined: "Combined", pipeline: "Pipeline", proposals: "Proposals", revenue: "Revenue", campaignResults: "Campaign Results", totalNeedsResults: "Total Needs Results", coiPerformance: "COI Performance", avgFee: "Avg Fee", avgDays: "Avg Days", statusProgression: "Status Progression", totalCOIs: "Total COIs", referrals: "Referrals", converted: "Converted", proposalFeeValue: "Proposal Fee Value", securedFeeValue: "Secured Fee Value", byIndustry: "By Industry", prospectStatus: "Prospect Status", statusDistribution: "Distribution by current status", leadSources: "Lead Sources", whereProspectsCome: "Where prospects come from", monthlyTrend: "Monthly Secured Value Trend", revenueOverTime: "Revenue secured over time", workSecuredByTeam: "Work Secured by Team Member", individualPerformance: "Individual performance breakdown" },
    pipeline: { badge: "Sales", title: "Pipeline", subtitle: "Manage your prospect pipeline and track sales progress", addProspect: "+ Add Prospect", totalProspects: "Total Prospects", active: "Active", meetings: "Meetings", proposals: "Proposals", secured: "Secured", proposalValue: "Proposal Value", securedValue: "Secured Value", newProspect: "New Prospect", saving: "Saving...", saveProspect: "Save Prospect", searchProspects: "Search prospects...", filterByOwner: "Filter by owner...", apply: "Apply", loadingData: "Loading pipeline data..." },
    coi: { badge: "Report", title: "COI Performance", subtitle: "Manage Centers of Influence and track referral metrics", refresh: "Refresh", coiRelationships: "COI Relationships", totalReferrals: "Total Referrals", converted: "Converted", conversionRate: "Conversion Rate", proposedFeeValue: "Proposed Fee Value", securedFeeValue: "Secured Fee Value", addCoi: "Add COI", addCoiDesc: "Add a new Center of Influence. COI names will appear in the Pipeline dropdown.", coiName: "COI Name", placeholderName: "Full name", email: "Email", placeholderEmail: "email{'@'}example.com", cellPhone: "Cell/Phone", placeholderPhone: "Phone number", entityCompany: "Entity/Company", placeholderCompany: "Company name", position: "Position", placeholderPosition: "Job title", industry: "Industry", selectIndustry: "Select industry...", leadPartner: "Lead Relationship Partner", selectPartner: "Select partner...", relationshipSupport: "Relationship Support", selectStaff: "Select staff...", saving: "Saving...", addCoiBtn: "Add COI", directory: "COI Directory", directoryDesc: "All registered Centers of Influence. Use these names in the Pipeline COI dropdown.", removing: "Removing...", removeSelected: "Remove Selected ({count})", loadingEntries: "Loading COI entries...", selectAll: "Select all", name: "Name", entity: "Entity", cell: "Cell", couldWe: "Could We", howWouldWe: "How Would We", willWe: "Will We", testReview: "Test/Review", noEntries: "No COI entries yet. Add your first COI above.", loadingSummary: "Loading COI summary...", performanceTitle: "Referral Performance by COI", performanceDesc: "Data calculated from Pipeline entries where COI is selected.", referrals: "Referrals", active: "Active", noReferralData: "No referral data yet. Assign COIs to prospects in the Pipeline page." },
    blog: { badge: "Blog", title: "Blog Studio", subtitle: "Create and manage blog content with AI-powered drafts", savedInputs: "Saved Inputs", drafts: "Drafts", finals: "Finals", blogInputs: "Blog Inputs", topic: "Topic", topicPlaceholder: "e.g., Interest rates and small business cashflow", audience: "Audience", objective: "Objective", tone: "Tone", length: "Length", wordCount: "Word Count", wordCountPlaceholder: "e.g., 250-325", cta: "CTA", authorType: "Author Type", author: "Author", selectAuthor: "Select author...", principles: "Principles", principle: "Principle", detail: "Detail", references: "Reference Documents", refHint: "Select source documents or URLs to help AI generate your blog", doc: "Doc", noReferences: "No reference documents yet", addReference: "+ Add Reference", refTitle: "Title", refTitlePlaceholder: "e.g., Q1 2024 Market Analysis", refType: "Type", document: "Document", urlLink: "URL Link", content: "Content", contentPlaceholder: "Paste your reference document text here...", topicOptional: "Topic (optional)", topicOptionalPlaceholder: "e.g., Interest Rates, Tax Planning", saveReference: "Save Reference", saveInputs: "Save Inputs", generateDraft: "Generate Draft", generateFinal: "Generate Final", generating: "Generating...", saveDraft: "Save Draft", saveFinal: "Save Final", restore: "Restore", draftOutlines: "Draft Outlines", searchDrafts: "Search drafts", pinnedOnly: "Pinned only", pinned: "Pinned", unpinned: "Unpinned", pin: "Pin", unpin: "Unpin", finalPosts: "Final Posts", searchFinals: "Search finals", duplicateToDraft: "Duplicate to Draft", draftOutline: "Draft Outline", words: "words", editMode: "Edit Mode", saveChanges: "Save Changes", aiInstructions: "AI Instructions for Final Generation", aiInstructionsHint: "Add specific guidance for the AI when generating the final article (optional)", aiInstructionsPlaceholder: "e.g., Include specific statistics with sources and dates. Emphasize practical takeaways. Add a compelling opening hook...", finalPost: "Final Post", target: "target", polishLevel: "Polish Level" },
    team: { badge: "Team", title: "Team Performance", subtitle: "Track team metrics, proposals, and secured work at a glance", teamMembers: "Team Members", totalProspects: "Total Prospects", proposalsSent: "Proposals Sent", securedValue: "Secured Value", loadingSummary: "Loading team summary...", teamMember: "Team Member", prospects: "Prospects", approaches: "Approaches", meetings: "Meetings", proposals: "Proposals", proposalValue: "Proposal Value", secured: "Secured", approachConv: "Approach Conv", avgProposal: "Avg Proposal", securedConv: "Secured Conv", active: "Active", awaitResearch: "Await Research", completed: "Completed", dead: "Dead", onHold: "On Hold" },
    lists: { badge: "Configuration", title: "Lists", subtitle: "Manage dropdown options used throughout the Sales Tracker", loading: "Loading lists...", saved: "Saved", failedToSave: "Failed to save", infoBanner: "These lists define the dropdown options available in Sales Activity, COI Development, and other areas. Changes here will affect what options are available when entering data.", items: "items", moveUp: "Move up", moveDown: "Move down", remove: "Remove", addNewItem: "Add new item...", usageGuideTitle: "How Lists Are Used", prospectStatus: "Prospect Status", prospectStatusDesc: "Controls the status dropdown in Sales Activity. Rows are color-coded based on status.", prospectSource: "Prospect Source", prospectSourceDesc: "Tracks where leads come from. Used in dashboard charts for source analysis.", approachStyle: "Approach Style", approachStyleDesc: "Documents how you first contacted the prospect. Important for measuring approach effectiveness.", salesStyle: "Sales Style", salesStyleDesc: "Campaign vs Total Needs tracking. Each has its own funnel metrics on the dashboard.", totalNeedsStage: "Total Needs Stage", totalNeedsStageDesc: "For Total Needs sales, tracks progression through the 5-stage process.", industry: "Industry", industryDesc: "Used in both Sales Activity and COI Development for industry segmentation." }
  },
  es: {
    app: { title: "Centro de Comando de Ventas" },
    nav: { home: "Inicio", dashboard: "Panel", pipeline: "Embudo", team: "Equipo", coi: "CDI", blog: "Blog", lists: "Listas" },
    auth: { signIn: "Iniciar Sesión", signOut: "Cerrar Sesión", signingIn: "Iniciando sesión...", email: "Correo Electrónico", password: "Contraseña" },
    common: { save: "Guardar", cancel: "Cancelar", delete: "Eliminar", edit: "Editar", add: "Agregar", search: "Buscar", loading: "Cargando...", loadingDashboard: "Cargando panel...", noData: "No hay datos disponibles", confirm: "Confirmar", yes: "Sí", no: "No", refresh: "Actualizar", active: "activo", days: "días", unassigned: "Sin asignar", na: "N/D" },
    language: { select: "Idioma", en: "Inglés", es: "Español", fr: "Francés" },
    login: { title: "Iniciar Sesión", subtitle: "Usa tu cuenta para acceder a los datos de tu inquilino.", emailPlaceholder: "tu{'@'}ejemplo.com", passwordPlaceholder: "********", hint: "Primera configuración: establece ADMIN_EMAIL y ADMIN_PASSWORD en .env e inicia sesión con esos valores." },
    home: { badge: "Inicio", title: "Centro de Comando de Ventas", subtitle: "Navega entre panel, pipeline, equipo, COI y vistas de blog", filteredProspects: "Prospectos Filtrados", activeStaff: "Entradas de Personal Activo", securedValue: "Valor Asegurado", coiRecords: "Registros COI", dashboard: "Panel", dashboardDesc: "KPIs principales para acercamientos, reuniones, propuestas y trabajo asegurado.", dashboardCharts: "Gráficos del Panel", dashboardChartsDesc: "Ve el resumen de KPIs y las tendencias visuales juntos en un solo lugar.", pipeline: "Pipeline", pipelineDesc: "Tabla detallada del pipeline con la vista de prospectos de trabajo.", team: "Equipo", teamDesc: "Abre el informe del equipo sin buscar entre pestañas.", coi: "COI", coiDesc: "Ve directamente a la actividad de desarrollo de referencias y registros.", blog: "Blog", blogDesc: "Abre el flujo de contenido, entradas guardadas, borradores y publicaciones finales.", todayGlance: "Resumen de Hoy", prospectName: "Nombre del Prospecto", businessName: "Nombre del Negocio", teamMember: "Miembro del Equipo", status: "Estado", securedValueCol: "Valor Asegurado", whatEachSection: "Qué Te Ofrece Cada Sección", infoDashboard: "El panel ahora incluye tanto números principales como gráficos.", infoTrends: "Las tendencias visuales están directamente debajo del resumen de KPIs.", infoPipeline: "Pipeline es la vista de trabajo para exportar y seguimiento.", rowsLoaded: "Filas de equipo cargadas: {team} | Filas COI cargadas: {coi}" },
    dashboard: { badge: "Analítica", title: "Panel de Ventas", subtitle: "Información en tiempo real sobre tu pipeline de ventas y rendimiento del equipo", totalProspects: "Total de Prospectos en Pipeline", approachMeeting: "Acercamiento → Reunión", meetingProposal: "Reunión → Propuesta", proposalSecured: "Propuesta → Asegurado", overallWinRate: "Tasa de Éxito General", pipelineValue: "Valor del Pipeline", workSecured: "Trabajo Asegurado", outstandingProposals: "Propuestas pendientes", totalClosedValue: "Valor total cerrado", combined: "Combinado", pipeline: "Pipeline", proposals: "Propuestas", revenue: "Ingresos", campaignResults: "Resultados de Campaña", totalNeedsResults: "Resultados de Necesidades Totales", coiPerformance: "Rendimiento COI", avgFee: "Tarifa Prom.", avgDays: "Días Prom.", statusProgression: "Progresión de Estado", totalCOIs: "Total de COIs", referrals: "Referencias", converted: "Convertidos", proposalFeeValue: "Valor de Tarifa de Propuesta", securedFeeValue: "Valor de Tarifa Asegurada", byIndustry: "Por Industria", prospectStatus: "Estado del Prospecto", statusDistribution: "Distribución por estado actual", leadSources: "Fuentes de Leads", whereProspectsCome: "De dónde vienen los prospectos", monthlyTrend: "Tendencia Mensual de Valor Asegurado", revenueOverTime: "Ingresos asegurados a lo largo del tiempo", workSecuredByTeam: "Trabajo Asegurado por Miembro del Equipo", individualPerformance: "Desglose de rendimiento individual" },
    pipeline: { badge: "Ventas", title: "Embudo de Ventas", subtitle: "Gestiona tu pipeline de prospectos y sigue el progreso de ventas", addProspect: "+ Agregar Prospecto", totalProspects: "Total de Prospectos", active: "Activos", meetings: "Reuniones", proposals: "Propuestas", secured: "Asegurados", proposalValue: "Valor de Propuesta", securedValue: "Valor Asegurado", newProspect: "Nuevo Prospecto", saving: "Guardando...", saveProspect: "Guardar Prospecto", searchProspects: "Buscar prospectos...", filterByOwner: "Filtrar por propietario...", apply: "Aplicar", loadingData: "Cargando datos del pipeline..." },
    coi: { badge: "Informe", title: "Rendimiento CDI", subtitle: "Gestiona Centros de Influencia y sigue métricas de referencias", refresh: "Actualizar", coiRelationships: "Relaciones COI", totalReferrals: "Total de Referencias", converted: "Convertidos", conversionRate: "Tasa de Conversión", proposedFeeValue: "Valor de Tarifa Propuesta", securedFeeValue: "Valor de Tarifa Asegurada", addCoi: "Agregar COI", addCoiDesc: "Agrega un nuevo Centro de Influencia. Los nombres de COI aparecerán en el menú de Pipeline.", coiName: "Nombre del COI", placeholderName: "Nombre completo", email: "Correo", placeholderEmail: "correo{'@'}ejemplo.com", cellPhone: "Celular/Teléfono", placeholderPhone: "Número de teléfono", entityCompany: "Entidad/Empresa", placeholderCompany: "Nombre de empresa", position: "Posición", placeholderPosition: "Cargo", industry: "Industria", selectIndustry: "Seleccionar industria...", leadPartner: "Socio Principal de Relación", selectPartner: "Seleccionar socio...", relationshipSupport: "Soporte de Relación", selectStaff: "Seleccionar personal...", saving: "Guardando...", addCoiBtn: "Agregar COI", directory: "Directorio COI", directoryDesc: "Todos los Centros de Influencia registrados. Usa estos nombres en el menú COI del Pipeline.", removing: "Eliminando...", removeSelected: "Eliminar Seleccionados ({count})", loadingEntries: "Cargando entradas COI...", selectAll: "Seleccionar todo", name: "Nombre", entity: "Entidad", cell: "Celular", couldWe: "Podríamos", howWouldWe: "Cómo lo Haríamos", willWe: "Lo Haremos", testReview: "Prueba/Revisión", noEntries: "Sin entradas COI aún. Agrega tu primer COI arriba.", loadingSummary: "Cargando resumen COI...", performanceTitle: "Rendimiento de Referencias por COI", performanceDesc: "Datos calculados desde entradas del Pipeline donde se seleccionó COI.", referrals: "Referencias", active: "Activo", noReferralData: "Sin datos de referencias aún. Asigna COIs a prospectos en la página Pipeline." },
    blog: { badge: "Blog", title: "Estudio de Blog", subtitle: "Crea y gestiona contenido de blog con borradores potenciados por IA", savedInputs: "Entradas Guardadas", drafts: "Borradores", finals: "Finales", blogInputs: "Entradas de Blog", topic: "Tema", topicPlaceholder: "ej., Tasas de interés y flujo de caja de pequeñas empresas", audience: "Audiencia", objective: "Objetivo", tone: "Tono", length: "Longitud", wordCount: "Cantidad de Palabras", wordCountPlaceholder: "ej., 250-325", cta: "CTA", authorType: "Tipo de Autor", author: "Autor", selectAuthor: "Seleccionar autor...", principles: "Principios", principle: "Principio", detail: "Detalle", references: "Documentos de Referencia", refHint: "Selecciona documentos fuente o URLs para ayudar a la IA a generar tu blog", doc: "Doc", noReferences: "Sin documentos de referencia aún", addReference: "+ Agregar Referencia", refTitle: "Título", refTitlePlaceholder: "ej., Análisis de Mercado Q1 2024", refType: "Tipo", document: "Documento", urlLink: "Enlace URL", content: "Contenido", contentPlaceholder: "Pega el texto de tu documento de referencia aquí...", topicOptional: "Tema (opcional)", topicOptionalPlaceholder: "ej., Tasas de Interés, Planificación Fiscal", saveReference: "Guardar Referencia", saveInputs: "Guardar Entradas", generateDraft: "Generar Borrador", generateFinal: "Generar Final", generating: "Generando...", saveDraft: "Guardar Borrador", saveFinal: "Guardar Final", restore: "Restaurar", draftOutlines: "Borradores de Esquema", searchDrafts: "Buscar borradores", pinnedOnly: "Solo fijados", pinned: "Fijado", unpinned: "No fijado", pin: "Fijar", unpin: "Desfijar", finalPosts: "Publicaciones Finales", searchFinals: "Buscar finales", duplicateToDraft: "Duplicar a Borrador", draftOutline: "Esquema de Borrador", words: "palabras", editMode: "Modo Edición", saveChanges: "Guardar Cambios", aiInstructions: "Instrucciones de IA para Generación Final", aiInstructionsHint: "Agrega guía específica para la IA al generar el artículo final (opcional)", aiInstructionsPlaceholder: "ej., Incluir estadísticas específicas con fuentes y fechas. Enfatizar conclusiones prácticas. Agregar un gancho de apertura atractivo...", finalPost: "Publicación Final", target: "objetivo", polishLevel: "Nivel de Pulido" },
    team: { badge: "Equipo", title: "Rendimiento del Equipo", subtitle: "Sigue métricas del equipo, propuestas y trabajo asegurado de un vistazo", teamMembers: "Miembros del Equipo", totalProspects: "Total de Prospectos", proposalsSent: "Propuestas Enviadas", securedValue: "Valor Asegurado", loadingSummary: "Cargando resumen del equipo...", teamMember: "Miembro del Equipo", prospects: "Prospectos", approaches: "Acercamientos", meetings: "Reuniones", proposals: "Propuestas", proposalValue: "Valor de Propuesta", secured: "Asegurado", approachConv: "Conv. Acercamiento", avgProposal: "Propuesta Prom.", securedConv: "Conv. Asegurado", active: "Activo", awaitResearch: "Esperando Investigación", completed: "Completado", dead: "Muerto", onHold: "En Espera" },
    lists: { badge: "Configuración", title: "Listas", subtitle: "Gestiona opciones de menú desplegable usadas en el Sales Tracker", loading: "Cargando listas...", saved: "Guardado", failedToSave: "Error al guardar", infoBanner: "Estas listas definen las opciones de menú desplegable disponibles en Actividad de Ventas, Desarrollo COI y otras áreas. Los cambios aquí afectarán qué opciones están disponibles al ingresar datos.", items: "elementos", moveUp: "Mover arriba", moveDown: "Mover abajo", remove: "Eliminar", addNewItem: "Agregar nuevo elemento...", usageGuideTitle: "Cómo se Usan las Listas", prospectStatus: "Estado del Prospecto", prospectStatusDesc: "Controla el menú de estado en Actividad de Ventas. Las filas tienen código de color según el estado.", prospectSource: "Fuente del Prospecto", prospectSourceDesc: "Rastrea de dónde vienen los leads. Usado en gráficos del panel para análisis de fuentes.", approachStyle: "Estilo de Acercamiento", approachStyleDesc: "Documenta cómo contactaste primero al prospecto. Importante para medir efectividad de acercamiento.", salesStyle: "Estilo de Ventas", salesStyleDesc: "Seguimiento de Campaña vs Necesidades Totales. Cada uno tiene sus propias métricas de embudo en el panel.", totalNeedsStage: "Etapa de Necesidades Totales", totalNeedsStageDesc: "Para ventas de Necesidades Totales, sigue la progresión a través del proceso de 5 etapas.", industry: "Industria", industryDesc: "Usado tanto en Actividad de Ventas como en Desarrollo COI para segmentación por industria." }
  },
  fr: {
    app: { title: "Centre de Commande des Ventes" },
    nav: { home: "Accueil", dashboard: "Tableau de Bord", pipeline: "Entonnoir", team: "Équipe", coi: "CdI", blog: "Blog", lists: "Listes" },
    auth: { signIn: "Se Connecter", signOut: "Se Déconnecter", signingIn: "Connexion en cours...", email: "E-mail", password: "Mot de Passe" },
    common: { save: "Enregistrer", cancel: "Annuler", delete: "Supprimer", edit: "Modifier", add: "Ajouter", search: "Rechercher", loading: "Chargement...", loadingDashboard: "Chargement du tableau de bord...", noData: "Aucune donnée disponible", confirm: "Confirmer", yes: "Oui", no: "Non", refresh: "Actualiser", active: "actif", days: "jours", unassigned: "Non assigné", na: "N/D" },
    language: { select: "Langue", en: "Anglais", es: "Espagnol", fr: "Français" },
    login: { title: "Se Connecter", subtitle: "Utilisez votre compte pour accéder aux données de votre locataire.", emailPlaceholder: "vous{'@'}exemple.com", passwordPlaceholder: "********", hint: "Première configuration: définissez ADMIN_EMAIL et ADMIN_PASSWORD dans .env et connectez-vous avec ces valeurs." },
    home: { badge: "Accueil", title: "Centre de Commande des Ventes", subtitle: "Naviguez entre tableau de bord, pipeline, équipe, COI et vues blog", filteredProspects: "Prospects Filtrés", activeStaff: "Entrées du Personnel Actif", securedValue: "Valeur Sécurisée", coiRecords: "Enregistrements COI", dashboard: "Tableau de Bord", dashboardDesc: "KPIs principaux pour approches, réunions, propositions et travail sécurisé.", dashboardCharts: "Graphiques du Tableau de Bord", dashboardChartsDesc: "Voyez le résumé des KPIs et les tendances visuelles ensemble en un seul endroit.", pipeline: "Pipeline", pipelineDesc: "Tableau détaillé du pipeline avec la vue des prospects de travail.", team: "Équipe", teamDesc: "Ouvrez le rapport d'équipe sans chercher dans les onglets.", coi: "COI", coiDesc: "Accédez directement à l'activité de développement des références et aux enregistrements.", blog: "Blog", blogDesc: "Ouvrez le flux de contenu, entrées sauvegardées, brouillons et publications finales.", todayGlance: "Aperçu d'Aujourd'hui", prospectName: "Nom du Prospect", businessName: "Nom de l'Entreprise", teamMember: "Membre de l'Équipe", status: "Statut", securedValueCol: "Valeur Sécurisée", whatEachSection: "Ce Que Chaque Section Vous Offre", infoDashboard: "Le tableau de bord inclut maintenant les chiffres clés et les graphiques.", infoTrends: "Les tendances visuelles sont directement sous le résumé des KPIs.", infoPipeline: "Pipeline est la vue de travail pour l'exportation et le suivi.", rowsLoaded: "Lignes d'équipe chargées: {team} | Lignes COI chargées: {coi}" },
    dashboard: { badge: "Analytique", title: "Tableau de Bord des Ventes", subtitle: "Informations en temps réel sur votre pipeline de ventes et performance de l'équipe", totalProspects: "Total des Prospects en Pipeline", approachMeeting: "Approche → Réunion", meetingProposal: "Réunion → Proposition", proposalSecured: "Proposition → Sécurisé", overallWinRate: "Taux de Réussite Global", pipelineValue: "Valeur du Pipeline", workSecured: "Travail Sécurisé", outstandingProposals: "Propositions en attente", totalClosedValue: "Valeur totale clôturée", combined: "Combiné", pipeline: "Pipeline", proposals: "Propositions", revenue: "Revenus", campaignResults: "Résultats de Campagne", totalNeedsResults: "Résultats des Besoins Totaux", coiPerformance: "Performance COI", avgFee: "Tarif Moy.", avgDays: "Jours Moy.", statusProgression: "Progression du Statut", totalCOIs: "Total des COIs", referrals: "Références", converted: "Convertis", proposalFeeValue: "Valeur de Tarif de Proposition", securedFeeValue: "Valeur de Tarif Sécurisée", byIndustry: "Par Industrie", prospectStatus: "Statut du Prospect", statusDistribution: "Distribution par statut actuel", leadSources: "Sources de Leads", whereProspectsCome: "D'où viennent les prospects", monthlyTrend: "Tendance Mensuelle de Valeur Sécurisée", revenueOverTime: "Revenus sécurisés au fil du temps", workSecuredByTeam: "Travail Sécurisé par Membre de l'Équipe", individualPerformance: "Détail de performance individuelle" },
    pipeline: { badge: "Ventes", title: "Entonnoir de Ventes", subtitle: "Gérez votre pipeline de prospects et suivez la progression des ventes", addProspect: "+ Ajouter Prospect", totalProspects: "Total des Prospects", active: "Actifs", meetings: "Réunions", proposals: "Propositions", secured: "Sécurisés", proposalValue: "Valeur de Proposition", securedValue: "Valeur Sécurisée", newProspect: "Nouveau Prospect", saving: "Enregistrement...", saveProspect: "Enregistrer Prospect", searchProspects: "Rechercher prospects...", filterByOwner: "Filtrer par propriétaire...", apply: "Appliquer", loadingData: "Chargement des données du pipeline..." },
    coi: { badge: "Rapport", title: "Performance CdI", subtitle: "Gérez les Centres d'Influence et suivez les métriques de références", refresh: "Actualiser", coiRelationships: "Relations COI", totalReferrals: "Total des Références", converted: "Convertis", conversionRate: "Taux de Conversion", proposedFeeValue: "Valeur des Tarifs Proposés", securedFeeValue: "Valeur des Tarifs Sécurisés", addCoi: "Ajouter COI", addCoiDesc: "Ajoutez un nouveau Centre d'Influence. Les noms COI apparaîtront dans le menu Pipeline.", coiName: "Nom du COI", placeholderName: "Nom complet", email: "E-mail", placeholderEmail: "email{'@'}exemple.com", cellPhone: "Portable/Téléphone", placeholderPhone: "Numéro de téléphone", entityCompany: "Entité/Société", placeholderCompany: "Nom de l'entreprise", position: "Poste", placeholderPosition: "Intitulé du poste", industry: "Industrie", selectIndustry: "Sélectionner industrie...", leadPartner: "Partenaire Principal", selectPartner: "Sélectionner partenaire...", relationshipSupport: "Support Relationnel", selectStaff: "Sélectionner personnel...", saving: "Enregistrement...", addCoiBtn: "Ajouter COI", directory: "Répertoire COI", directoryDesc: "Tous les Centres d'Influence enregistrés. Utilisez ces noms dans le menu COI du Pipeline.", removing: "Suppression...", removeSelected: "Supprimer Sélectionnés ({count})", loadingEntries: "Chargement des entrées COI...", selectAll: "Tout sélectionner", name: "Nom", entity: "Entité", cell: "Portable", couldWe: "Pourrions-nous", howWouldWe: "Comment le Ferions-nous", willWe: "Le Ferons-nous", testReview: "Test/Révision", noEntries: "Pas encore d'entrées COI. Ajoutez votre premier COI ci-dessus.", loadingSummary: "Chargement du résumé COI...", performanceTitle: "Performance des Références par COI", performanceDesc: "Données calculées à partir des entrées Pipeline où le COI est sélectionné.", referrals: "Références", active: "Actif", noReferralData: "Pas encore de données de références. Assignez des COIs aux prospects dans la page Pipeline." },
    blog: { badge: "Blog", title: "Studio de Blog", subtitle: "Créez et gérez du contenu de blog avec des brouillons assistés par IA", savedInputs: "Entrées Sauvegardées", drafts: "Brouillons", finals: "Finaux", blogInputs: "Entrées de Blog", topic: "Sujet", topicPlaceholder: "ex., Taux d'intérêt et trésorerie des petites entreprises", audience: "Audience", objective: "Objectif", tone: "Ton", length: "Longueur", wordCount: "Nombre de Mots", wordCountPlaceholder: "ex., 250-325", cta: "CTA", authorType: "Type d'Auteur", author: "Auteur", selectAuthor: "Sélectionner auteur...", principles: "Principes", principle: "Principe", detail: "Détail", references: "Documents de Référence", refHint: "Sélectionnez des documents sources ou URLs pour aider l'IA à générer votre blog", doc: "Doc", noReferences: "Pas encore de documents de référence", addReference: "+ Ajouter Référence", refTitle: "Titre", refTitlePlaceholder: "ex., Analyse de Marché Q1 2024", refType: "Type", document: "Document", urlLink: "Lien URL", content: "Contenu", contentPlaceholder: "Collez le texte de votre document de référence ici...", topicOptional: "Sujet (optionnel)", topicOptionalPlaceholder: "ex., Taux d'Intérêt, Planification Fiscale", saveReference: "Enregistrer Référence", saveInputs: "Enregistrer Entrées", generateDraft: "Générer Brouillon", generateFinal: "Générer Final", generating: "Génération...", saveDraft: "Enregistrer Brouillon", saveFinal: "Enregistrer Final", restore: "Restaurer", draftOutlines: "Esquisses de Brouillons", searchDrafts: "Rechercher brouillons", pinnedOnly: "Épinglés seulement", pinned: "Épinglé", unpinned: "Non épinglé", pin: "Épingler", unpin: "Désépingler", finalPosts: "Publications Finales", searchFinals: "Rechercher finaux", duplicateToDraft: "Dupliquer en Brouillon", draftOutline: "Esquisse de Brouillon", words: "mots", editMode: "Mode Édition", saveChanges: "Enregistrer Modifications", aiInstructions: "Instructions IA pour Génération Finale", aiInstructionsHint: "Ajoutez des conseils spécifiques pour l'IA lors de la génération de l'article final (optionnel)", aiInstructionsPlaceholder: "ex., Inclure des statistiques spécifiques avec sources et dates. Mettre en valeur les points pratiques. Ajouter une accroche d'ouverture captivante...", finalPost: "Publication Finale", target: "cible", polishLevel: "Niveau de Finition" },
    team: { badge: "Équipe", title: "Performance de l'Équipe", subtitle: "Suivez les métriques de l'équipe, propositions et travail sécurisé d'un coup d'œil", teamMembers: "Membres de l'Équipe", totalProspects: "Total des Prospects", proposalsSent: "Propositions Envoyées", securedValue: "Valeur Sécurisée", loadingSummary: "Chargement du résumé de l'équipe...", teamMember: "Membre de l'Équipe", prospects: "Prospects", approaches: "Approches", meetings: "Réunions", proposals: "Propositions", proposalValue: "Valeur de Proposition", secured: "Sécurisé", approachConv: "Conv. Approche", avgProposal: "Proposition Moy.", securedConv: "Conv. Sécurisé", active: "Actif", awaitResearch: "En Attente de Recherche", completed: "Terminé", dead: "Mort", onHold: "En Attente" },
    lists: { badge: "Configuration", title: "Listes", subtitle: "Gérez les options de menu déroulant utilisées dans le Sales Tracker", loading: "Chargement des listes...", saved: "Enregistré", failedToSave: "Échec de l'enregistrement", infoBanner: "Ces listes définissent les options de menu déroulant disponibles dans Activité de Ventes, Développement COI et autres zones. Les modifications ici affecteront quelles options sont disponibles lors de la saisie de données.", items: "éléments", moveUp: "Monter", moveDown: "Descendre", remove: "Supprimer", addNewItem: "Ajouter un nouvel élément...", usageGuideTitle: "Comment les Listes sont Utilisées", prospectStatus: "Statut du Prospect", prospectStatusDesc: "Contrôle le menu déroulant de statut dans Activité de Ventes. Les lignes sont codées par couleur selon le statut.", prospectSource: "Source du Prospect", prospectSourceDesc: "Trace d'où viennent les leads. Utilisé dans les graphiques du tableau de bord pour l'analyse des sources.", approachStyle: "Style d'Approche", approachStyleDesc: "Documente comment vous avez d'abord contacté le prospect. Important pour mesurer l'efficacité de l'approche.", salesStyle: "Style de Vente", salesStyleDesc: "Suivi Campagne vs Besoins Totaux. Chacun a ses propres métriques d'entonnoir sur le tableau de bord.", totalNeedsStage: "Étape Besoins Totaux", totalNeedsStageDesc: "Pour les ventes Besoins Totaux, suit la progression à travers le processus en 5 étapes.", industry: "Industrie", industryDesc: "Utilisé dans Activité de Ventes et Développement COI pour la segmentation par industrie." }
  }
};

export default defineNuxtPlugin((nuxtApp) => {
  const validLocales = ['en', 'es', 'fr'];

  // Read locale from cookie - use different methods for server vs client
  let savedLocale = 'en';

  if (import.meta.server) {
    // Server: read from request cookies via useCookie
    const localeCookie = useCookie<string>('i18n_locale');
    savedLocale = localeCookie.value && validLocales.includes(localeCookie.value) ? localeCookie.value : 'en';
  } else {
    // Client: read directly from document.cookie for reliability
    const match = document.cookie.match(/(?:^|; )i18n_locale=([^;]*)/);
    const cookieValue = match ? match[1] : null;
    savedLocale = cookieValue && validLocales.includes(cookieValue) ? cookieValue : 'en';
  }

  // Keep useCookie ref for SSR compatibility
  const localeCookie = useCookie<string>('i18n_locale', {
    maxAge: 60 * 60 * 24 * 365, // 1 year
    path: '/',
    sameSite: 'lax'
  });

  const i18n = createI18n({
    legacy: false,
    globalInjection: true,
    locale: savedLocale,
    fallbackLocale: 'en',
    messages
  });

  nuxtApp.vueApp.use(i18n);

  return {
    provide: {
      i18n: i18n.global,
      setLocale: (newLocale: string) => {
        if (validLocales.includes(newLocale)) {
          i18n.global.locale.value = newLocale;
          // Use both useCookie (for SSR) and direct cookie (for immediate browser write)
          localeCookie.value = newLocale;
          if (import.meta.client) {
            // Directly write to document.cookie to ensure it's set before reload
            const expires = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toUTCString();
            document.cookie = `i18n_locale=${newLocale}; expires=${expires}; path=/; SameSite=Lax`;
          }
        }
      }
    }
  };
});
